<<<<<<< HEAD
title: "WEB HECHA POR DAVID GARCIA"
description: "Mi sitio hecho por mi"
url: "https://peloco21.github.io"
baseurl: ""

# Redes Sociales
social_links:
  twitter: "https://twitter.com/tu_usuario"
  github: "https://github.com/peloco21"
  linkedin: "https://www.linkedin.com/in/tu_usuario"

# SEO
seo:
  title: "MI NUEVA WEB"
  description: "Explora contenido único y episodios destacados"
  author: "peloco21"

# Paginación
paginate: 6

# Plugins
plugins:
  - jekyll-seo-tag
=======
title: "WEB HECHA POR DAVID GARCIA"
description: "Mi sitio hecho por mi"
url: "https://peloco21.github.io"
baseurl: ""

# Redes Sociales
social_links:
  twitter: "https://twitter.com/tu_usuario"
  github: "https://github.com/peloco21"
  linkedin: "https://www.linkedin.com/in/tu_usuario"

# SEO
seo:
  title: "MI NUEVA WEB"
  description: "Explora contenido único y episodios destacados"
  author: "peloco21"

# Paginación
paginate: 6

# Plugins
plugins:
  - jekyll-seo-tag
>>>>>>> b5142198b07d7d737d45e8b7abed64a9c1740334
  - jekyll-paginate